server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/auth/ {
        proxy_pass http://auth-service:8000/;
    }
    location /api/lobby/ {
        proxy_pass http://lobby-service:8001/;
    }
    location /api/chess/ {
        proxy_pass http://chess-service:8002/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}