apiVersion: v1
kind: Secret
metadata:
  name: lobby-secret
  namespace: microservices
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://lobby_service:lobby_pass@postgres:5432/lobby_db

  SECRET_KEY: notasecret
  ALGORITHM: HS256