"""Init Tables

Revision ID: 5844cd2b1ea4
Revises: 
Create Date: 2026-03-12 23:05:46.505295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5844cd2b1ea4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_player_id', sa.UUID(), nullable=False),
    sa.Column('to_player_id', sa.UUID(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobbies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id_1', sa.UUID(), nullable=False),
    sa.Column('player_id_2', sa.UUID(), nullable=False),
    sa.Column('player_1_ready', sa.Boolean(), nullable=False),
    sa.Column('player_2_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_lobbies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_player_id', sa.UUID(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_lobbies')
    op.drop_table('lobbies')
    op.drop_table('invites')
    # ### end Alembic commands ###
