"""create game_invites and game_lobbies tables

Revision ID: 5ea9a09a8ae3
Revises: 
Create Date: 2026-03-08 23:09:57.246171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea9a09a8ae3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_player_id', sa.UUID(), nullable=False),
    sa.Column('to_player_id', sa.UUID(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_lobbies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_player_id', sa.UUID(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_lobbies')
    op.drop_table('game_invites')
    # ### end Alembic commands ###
