"""create games and game events tables

Revision ID: e4bfda47cd8b
Revises: 
Create Date: 2026-03-08 23:02:38.287669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bfda47cd8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('white_player_id', sa.UUID(), nullable=False),
    sa.Column('black_player_id', sa.UUID(), nullable=False),
    sa.Column('winner_player_id', sa.UUID(), nullable=True),
    sa.Column('is_draw', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('white_player_id <> black_player_id', name='ck_distinct_players'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('uci_move', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ply > 0', name='ck_game_events_ply_positive'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='uq_game_events_game_id_ply')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_events')
    op.drop_table('games')
    # ### end Alembic commands ###
