name: Auth CI

on:
  push:
    branches:
      - main
    paths:
      - 'Auth-Service/**'
      - '.github/workflows/auth-ci.yml'
      - '.github/workflows/_python-service-ci.yml'
  workflow_dispatch:

jobs:
  auth-ci:
    uses: ./.github/workflows/_python-service-ci.yml
    with:
      service_path: Auth-Service
