name: Lobby CI

on:
  push:
    branches:
      - main
    paths:
      - 'Lobby-Service/**'
      - '.github/workflows/lobby-ci.yml'
      - '.github/workflows/_python-service-ci.yml'
  workflow_dispatch:

jobs:
  lobby-ci:
    uses: ./.github/workflows/_python-service-ci.yml
    with:
      service_path: Lobby-Service
