name: Users CI

on:
  push:
    branches:
      - main
    paths:
      - 'Lobby-Service/**'
      - '.github/workflows/lobby-ci.yml'
      - '.github/workflows/_python-service-ci.yml'
  workflow_dispatch:

jobs:
  users-ci:
    uses: ./.github/workflows/_python-service-ci.yml
    with:
      service_path: users
      python_package: users
